version: "3"
services:
    strapi:
        container_name: strapi
        image: strapi/strapi:3.0.1
        restart: always
        environment:
            DATABASE_CLIENT: mongo
            DATABASE_NAME: strapi
            DATABASE_HOST: mongo
            DATABASE_PORT: 27017
            DATABASE_USERNAME: strapi
            DATABASE_PASSWORD: strapi
        links:
            - mongo:mongo
        volumes:
            - ../src/backend/app:/srv/app
        ports:
            - 1337:1337
    mongo:
        container_name: mongo
        build:
            context: ../docker/mongo
        restart: always
        tty: true
        environment:
            MONGO_INITDB_ROOT_USERNAME: strapi
            MONGO_INITDB_ROOT_PASSWORD: strapi
        volumes:
            - ../src/mongo/db:/data/db
            - ../src/mongo/configdb:/data/configdb
        ports:
            - 27017-27019:27017-27019
    express:
        container_name: mongo-express
        ports:
            - 8081:8081
        restart: always
        links:
            - mongo:mongo
        environment:
            ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: strapi
            ME_CONFIG_MONGODB_ADMINPASSWORD: strapi
        image: mongo-express
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        hostname: prometheus
        volumes:
            - ../src/prometheus:/etc/prometheus
        command: "--config.file=/etc/prometheus/prometheus.yaml"
        ports:
            - 9090:9090
        restart: always
    exporter:
        image: prom/node-exporter:latest
        container_name: exporter
        hostname: exporter
        ports:
            - 9100:9100
        restart: always
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
    grafana:
        image: grafana/grafana
        container_name: grafana
        hostname: grafana
        user: "1000" # dockerの起動ユーザーに合わせる
        ports:
            - 3000:3000
        volumes:
            - ../src/grafana:/var/lib/grafanad
        restart: always
    alertmanager:
        image: prom/alertmanager
        container_name: alertmanager
        hostname: alertmanager
        volumes:
            - ../src/alertmanager:/etc/alertmanager
        command: "--config.file=/etc/alertmanager/config.yaml"
        ports:
            - 9093:9093
        restart: always
