version: "3"
services:
    nginx:
        build:
            context: ../docker/nginx
        container_name: nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - ../src/nginx/html:/app
            - ../src/nginx/setting:/setting
            - ../src/nginx/default.conf:/etc/nginx/conf.d/default.conf