# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|


  config.vm.define 'develop' do |dev|
    dev.vm.box = "ubuntu/bionic64"
    dev.vm.hostname = 'development'
    # IP重複注意
    dev.vm.network "private_network",ip: "192.168.13.25"
    dev.vm.synced_folder "../../..", "/workspace",
      :mount_options => ["dmode=777,fmode=777"]
    dev.vm.provider "virtualbox" do |vbox|
      vbox.gui = false
      vbox.cpus = 2
      vbox.memory = 2048
    end
    dev.vm.provision :docker
    dev.vm.provision :docker_compose, compose_version: "1.25.5"
    # ポート重複注意
    dev.vm.network :forwarded_port, id: "ssh", guest: 22, host: 14425
    dev.vm.network :forwarded_port, guest: 27017, host: 27017
    dev.vm.network :forwarded_port, guest: 4200, host: 4200
    dev.vm.network :forwarded_port, guest: 8081, host: 8081

    ## Ansible
    #
    dev.vm.provision "ansible_local" do |ansible|
      ansible.playbook       = "develop.yml"
      ansible.version        = "latest"
      ansible.verbose        = false
      ansible.install        = true
      ansible.limit          = "develop"
      ansible.inventory_path = "hosts"
    end
  end
end
