# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

module VagrantPlugins
  module GuestLinux
    class Plugin < Vagrant.plugin("2")
      guest_capability("linux", "change_host_name") { Cap::ChangeHostName }
      guest_capability("linux", "configure_networks") { Cap::ConfigureNetworks }
    end
  end
end

Vagrant.configure("2") do |config|

  config.disksize.size = '25GB'
  config.vm.define 'develop' do |dev|
    dev.vm.box = "ailispaw/barge"
    dev.vm.hostname = 'development'
    # IP重複注意
    dev.vm.network "private_network",ip: "192.168.13.25"
    dev.vm.synced_folder "../../..", "/workspace",
      :mount_options => ["dmode=777,fmode=777"]
    dev.vm.provider "virtualbox" do |vbox|
      vbox.gui = false
      vbox.cpus = 2
      vbox.memory = 4096
    end
    # ポート重複注意
    dev.vm.network :forwarded_port, id: "ssh", guest: 22, host: 14425
    dev.vm.network :forwarded_port, guest: 27017, host: 27017
    dev.vm.network :forwarded_port, guest: 4200, host: 4200
    dev.vm.network :forwarded_port, guest: 8081, host: 8081
    dev.vm.network :forwarded_port, guest: 9090, host: 9090
    dev.vm.network :forwarded_port, guest: 9100, host: 9100
    dev.vm.network :forwarded_port, guest: 3000, host: 3000
    dev.vm.network :forwarded_port, guest: 9093, host: 9093

    dev.vm.provision :shell, run: "always", :inline => <<-EOT
      sudo /etc/init.d/docker restart latest
      docker version
      wget -L https://github.com/docker/compose/releases/download/1.14.0/docker-compose-`uname -s`-`uname -m`
      mv docker-compose-`uname -s`-`uname -m` /opt/bin/docker-compose
      chmod +x /opt/bin/docker-compose
      chown root:root /opt/bin/docker-compose
    EOT
  end
end
