- hosts: all
  become: yes
  gather_facts: True
  vars_files:
    - env.yml
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    - name: Install packages
      apt:
        name:
          - "git"
          - "python3"
          - "python3-pip"
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

    - name: Install packages
      apt:
        name:
          [
            "apt-transport-https",
            "ca-certificates",
            "curl",
            "software-properties-common",
            "nfs-common",
            "conntrack",
          ]
        state: present
        update_cache: yes

    - name: create group
      group: name={{usergroup.group.name}} gid={{usergroup.group.gid}}
      
    - name: add users that join to group (wheel and usergroup)
      user: name={{usergroup.user.name}} shell=/bin/bash uid={{usergroup.user.uid}} state=present password={{usergroup.user.password}} groups={{usergroup.user.group}}
    
    - name: user join to other group
      user: name={{usergroup.user.name}} append=yes groups={{usergroup.group.name}}
    
    - name: ~/.ssh for users exist
      file: path="/home/{{usergroup.user.name}}/.ssh" state=directory owner={{usergroup.user.name}} group={{usergroup.user.group}} mode=0700

    - name: Install Docker-CE
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
        update_cache: yes

    - name: usermod -aG docker
      user:
        name: hosokawa
        groups: docker
