version: "3"
services:
    strapi:
        container_name: strapi
        image: strapi/strapi:3.0.1
        environment:
            DATABASE_CLIENT: mongo
            DATABASE_NAME: strapi
            DATABASE_HOST: mongo
            DATABASE_PORT: 27017
            DATABASE_USERNAME: strapi
            DATABASE_PASSWORD: strapi
        links:
            - mongo:mongo
        volumes:
            - ./backend/app:/srv/app
        ports:
            - "1337:1337"
    mongo:
        container_name: mongo
        build:
            context: ./docker/mongo
        tty: true
        environment:
            MONGO_INITDB_ROOT_USERNAME: strapi
            MONGO_INITDB_ROOT_PASSWORD: strapi
        volumes:
            - mongodata:/data
        ports:
            - "27017:27017"
    express:
        container_name: mongo-express
        ports:
            - "8081:8081"
        restart: always
        links:
            - mongo:mongo
        environment:
            ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: strapi
            ME_CONFIG_MONGODB_ADMINPASSWORD: strapi
        image: mongo-express
    angular:
        container_name: angular
        build:
            context: ./docker/angular
        ports:
            - "4200:4200"
        volumes:
            - ./frontend:/src
            - ./frontend/node_modules
        working_dir: /src
        tty: true
        environment:
            NG_CLI_ANALYTICS: "ci"
        command: >
            bash -c "yarn install &&
            ng serve --host 0.0.0.0  --poll=1000"
volumes:
    mongodata:
