# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|


  config.vm.define 'staging' do |stg|
    stg.vm.box = "ubuntu/bionic64"
    stg.vm.hostname = 'srageing'
    stg.vm.network "private_network",ip: "192.168.13.27"
    stg.vm.provider "virtualbox" do |vbox|
      vbox.gui = false
      vbox.cpus = 2
      vbox.memory = 2048
    end
    # ポート重複注意
    stg.vm.network :forwarded_port, id: "ssh", guest: 22, host: 14428
    stg.vm.provision "shell", privileged: false, inline: <<-SHELL
      sudo apt-add-repository ppa:ansible/ansible
      sudo apt-get update
      sudo apt-get upgrade
      sudo apt-get install -y ansible
    SHELL
  end
end
