name: only master branch
 
on:
  push:
    branches:
      - master
 
jobs:
  deploy:
 
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key of target
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa-target
          known_hosts: ${{ secrets.KNOWN_HOSTS_OF_TARGET }} # will be appended!
          config: |                                         # will be appended!
            Host target
              HostName 118.27.33.240
              User user-of-target
              IdentityFile ~/.ssh/id_rsa-target

      - name: rsync deploy
        run: rsync -auzrv -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 22" ./test222  root@118.27.33.240:/workspace/
